### ISSUE TITLE
Ai uitat ceva

### ISSUE THREAD

**Issue by Vasile2k** [Haurentziu/Astronomy-Toolkit#11]
In index.html pe linia 76 ai asa:

```html
<li>Random colors generated using <a href = "https://github.com/davidmerfield/randomColor"></a></li>
```

Link-ul ala nu e pus nicaieri, scrie si tu un cuvant acolo in ```<a>```

**Comment by Vasile2k** [comment]
PLZZZ FIX! APP CANNOT WORK! DRINK VODKA PLAY DOTKA~!1!

**Comment by Haurentziu** [comment]
FIXED!!!! GTFO YOU FUCKING PIECE OF SHEET!
